public class ActiveSubscriptions
{
    public long id { get; set; }
    public long? primarysub { get; set; }
    public byte colfreq { get; set; }
    public short? frequn { get; set; }
    public long? colcur { get; set; }
    public decimal? cashamt { get; set; }
    public decimal? colamt { get; set; }
    public long? packageid { get; set; }
    public string sddesc { get; set; }
    public DateTime? endate { get; set; }
    public long? persid { get; set; }
    public long? headmem { get; set; }
    public string fn { get; set; }
    public string sn { get; set; }
    public byte stat { get; set; }
    public byte colmet { get; set; }
    public long? acnt { get; set; }
    public long? payitem { get; set; }
    public long? positem { get; set; }
    public long siteid { get; set; }
    public string sitedesc { get; set; }
    public long? sitegrp { get; set; }
    public long? sitecurr { get; set; }
    public DateTime? findate { get; set; }
    public DateTime? nxdate { get; set; }
    public string ddrcolcod { get; set; }
    public DateTime? prevdate { get; set; }
    public decimal? ovrdam { get; set; }
    public decimal? ovrdnx { get; set; }
    public long? accOwner { get; set; }
    public string productCode { get; set; }
    public string nlCode { get; set; }
    public decimal? loyptcrd { get; set; }
    public decimal? loyptdeb { get; set; }
    public decimal? preamount { get; set; }
    public string preperiod { get; set; }
    public string acpFn { get; set; }
    public string acpSn { get; set; }
    public long? PrimaryID { get; set; }
    public byte rectyp { get; set; }
    public int PrimaryActive { get; set; }
}
