public class CCEFromOccurrence
{
    public long id { get; set; }
    public long grp { get; set; }
    public string mnem { get; set; }
    public string desc { get; set; }
    public string longdesc { get; set; }
    public long? cceimage { get; set; }
    public string alert { get; set; }
    public string http { get; set; }
    public string videourl { get; set; }
    public short? nocls { get; set; }
    public byte subtype { get; set; }
    public long cceg { get; set; }
    public long? ccecat { get; set; }
    public long? emapp { get; set; }
    public long? app { get; set; }
    public long? fullapp { get; set; }
    public decimal dayad { get; set; }
    public decimal dayadweb { get; set; }
    public decimal hourcnc { get; set; }
    public decimal hourgrace { get; set; }
    public byte? ordlev { get; set; }
    public int maxatt { get; set; }
    public int minatt { get; set; }
    public int maxwait { get; set; }
    public short seqno { get; set; }
    public byte payopt { get; set; }
    public bool waitlist { get; set; }
    public bool skipfree { get; set; }
    public bool enablecce { get; set; }
    public short preptime { get; set; }
    public short recotime { get; set; }
    public long? intprof { get; set; }
    public bool? allowvis { get; set; }
    public byte? minage { get; set; }
    public byte? maxage { get; set; }
    public byte allgend { get; set; }
    public bool proratachg { get; set; }
    public bool prorataref { get; set; }
    public long? UpsellOption { get; set; }
    public string waitsmstxt { get; set; }
    public short? wlnotifyoverride { get; set; }
    public long? waiverid { get; set; }
    public long? appearwaiverincomp { get; set; }
    public long? appearwaivercomp { get; set; }
    public long? goalid { get; set; }
    public long? batch { get; set; }
    public DateTime? lastupd { get; set; }
}
