public class GetDepositItemsForSiteAndUser
{
    public long DepositID { get; set; }
    public string Description { get; set; }
    public decimal PercentageAmount { get; set; }
    public int? showOrder { get; set; }
    public long? batch { get; set; }
    public DateTime? lastupd { get; set; }
    public long id { get; set; }
    public long site { get; set; }
    public long Deposit { get; set; }
    public long? batch { get; set; }
    public DateTime? lastupd { get; set; }
    public long DepositAccessID { get; set; }
    public long accessRights { get; set; }
    public long Deposit { get; set; }
    public long? batch { get; set; }
    public DateTime? lastupd { get; set; }
    public long id { get; set; }
    public string mnem { get; set; }
    public string desc { get; set; }
    public long? statapp { get; set; }
    public long? taskapp { get; set; }
    public byte acclev { get; set; }
    public byte memoffsl { get; set; }
    public bool allnl { get; set; }
    public long? viscli { get; set; }
    public long? rocli { get; set; }
    public byte tabone { get; set; }
    public byte tabtwo { get; set; }
    public byte tabthree { get; set; }
    public byte tabfour { get; set; }
    public byte tabfive { get; set; }
    public string starttab { get; set; }
    public string allowtab { get; set; }
    public long? subed { get; set; }
    public long? batch { get; set; }
    public DateTime? lastupd { get; set; }
    public long id { get; set; }
    public long susid { get; set; }
    public long secgrp { get; set; }
    public long? batch { get; set; }
    public DateTime? lastupd { get; set; }
    public long id { get; set; }
    public long sysusid { get; set; }
    public long sid { get; set; }
    public short prord { get; set; }
    public long? sitevwhen { get; set; }
    public long? mxview { get; set; }
    public long? resid { get; set; }
    public long? batch { get; set; }
    public DateTime? lastupd { get; set; }
}
