public class GetGroup
{
    public long id { get; set; }
    public string mnem { get; set; }
    public string desc { get; set; }
    public long? org { get; set; }
    public long? cont { get; set; }
    public string suptxt { get; set; }
    public long? intprof { get; set; }
    public long? siteprof { get; set; }
    public long? memstatlap { get; set; }
    public long? memstatdef { get; set; }
    public long? pospackcase { get; set; }
    public long? defprofweb { get; set; }
    public long? defprofapp { get; set; }
    public long? defprofchk { get; set; }
    public long? corpprof { get; set; }
    public long? qcef { get; set; }
    public long? qcemf { get; set; }
    public long? spabid { get; set; }
    public long? playlink { get; set; }
    public long? CheckInpos { get; set; }
    public long? OverStaypos { get; set; }
    public long? InitialFeepos { get; set; }
    public long? rokclink { get; set; }
    public long? rokbook { get; set; }
    public long? rokacnt { get; set; }
    public long? roknotes { get; set; }
    public long? roktask { get; set; }
    public long? rokfhis { get; set; }
    public long? rokacd { get; set; }
    public long? rokclino { get; set; }
    public long? rokitsklst { get; set; }
    public long? rokswipeid { get; set; }
    public long? rokusernameid { get; set; }
    public long? rokconflt { get; set; }
    public long? rokconfltpk { get; set; }
    public long? roktuslp { get; set; }
    public long? rokswpnt { get; set; }
    public long? rokrefacc { get; set; }
    public long? ssconch { get; set; }
    public string sortreg { get; set; }
    public string acntreg { get; set; }
    public string accnamreg { get; set; }
    public string phonereg { get; set; }
    public long? rokaccntadd { get; set; }
    public string sortregerror { get; set; }
    public string acntregerror { get; set; }
    public string accnamregerror { get; set; }
    public string phoneregerror { get; set; }
    public long? roktaskass { get; set; }
    public string adminemail { get; set; }
    public string ddidreg { get; set; }
    public string ddiderr { get; set; }
    public long? rokcourseconf { get; set; }
    public long? rokCheckIn { get; set; }
    public long? rokOverstayCalc { get; set; }
    public long? batch { get; set; }
    public DateTime? lastupd { get; set; }
}
