public class GetPersonByRemoteNumber
{
    public long id { get; set; }
    public string sn { get; set; }
    public string sn2 { get; set; }
    public string fn { get; set; }
    public string fn2 { get; set; }
    public string title { get; set; }
    public long? titlelk { get; set; }
    public string sex { get; set; }
    public DateTime? dob { get; set; }
    public string add1 { get; set; }
    public string add2 { get; set; }
    public string add3 { get; set; }
    public string addtwn { get; set; }
    public long? country { get; set; }
    public string pcod { get; set; }
    public string compnm { get; set; }
    public string badd1 { get; set; }
    public string badd2 { get; set; }
    public string badd3 { get; set; }
    public string baddtwn { get; set; }
    public long? bcountry { get; set; }
    public string bpcod { get; set; }
    public string oadd1 { get; set; }
    public string oadd2 { get; set; }
    public string oadd3 { get; set; }
    public string oaddtwn { get; set; }
    public long? ocountry { get; set; }
    public string opcod { get; set; }
    public string htele { get; set; }
    public string otele { get; set; }
    public string mtele { get; set; }
    public string mtele2 { get; set; }
    public string email { get; set; }
    public string email2 { get; set; }
    public string remid { get; set; }
    public string remnum { get; set; }
    public string swipe { get; set; }
    public string swipe2 { get; set; }
    public DateTime? joindate { get; set; }
    public DateTime? credat { get; set; }
    public long? headmem { get; set; }
    public long? prof { get; set; }
    public string proftxt { get; set; }
    public decimal? credlim { get; set; }
    public bool allcred { get; set; }
    public string memnote { get; set; }
    public long? src { get; set; }
    public long? memprf { get; set; }
    public long? memstat { get; set; }
    public bool onhold { get; set; }
    public string onholdreas { get; set; }
    public long? climage { get; set; }
    public long? viptyp { get; set; }
    public long? salesps { get; set; }
    public long? creby { get; set; }
    public short? entryrem { get; set; }
    public string webusr { get; set; }
    public string webpass { get; set; }
    public string webphrs { get; set; }
    public string snsx { get; set; }
    public string fnsx { get; set; }
    public string sal1 { get; set; }
    public string sal2 { get; set; }
    public string promocode { get; set; }
    public byte rectyp { get; set; }
    public DateTime? debtdate { get; set; }
    public bool allwmrktng { get; set; }
    public bool allwcmpgn { get; set; }
    public bool? registerCards { get; set; }
    public bool invalidemail { get; set; }
    public long? batch { get; set; }
    public DateTime? lastupd { get; set; }
}
