public class GetServiceDefinition
{
    public long id { get; set; }
    public long grp { get; set; }
    public string mnem { get; set; }
    public string desc { get; set; }
    public byte colfreq { get; set; }
    public long? proratepositem { get; set; }
    public short? frequn { get; set; }
    public long? colcur { get; set; }
    public short prio { get; set; }
    public long? categ { get; set; }
    public long? class { get; set; }
    public long? type { get; set; }
    public long? bokrt { get; set; }
    public short seq { get; set; }
    public bool allent { get; set; }
    public long? memstat { get; set; }
    public long? autoarfn { get; set; }
    public long? autoarren { get; set; }
    public short? maxentry { get; set; }
    public short? sper { get; set; }
    public byte? sperunit { get; set; }
    public bool rols { get; set; }
    public string proratrokold { get; set; }
    public long? rokprorate { get; set; }
    public long? rokconval { get; set; }
    public long? roksubsid { get; set; }
    public long? rokcontend { get; set; }
    public bool act { get; set; }
    public bool colinc { get; set; }
    public long? incpayitem { get; set; }
    public bool immPostCharge { get; set; }
    public long? nextdef { get; set; }
    public long? rokincdef { get; set; }
    public bool mandrevert { get; set; }
    public long? rokrefno { get; set; }
    public long? defgrp { get; set; }
    public long? intprf { get; set; }
    public long? rokendate { get; set; }
    public bool chargeprim { get; set; }
    public long? roknextcol { get; set; }
    public long? batch { get; set; }
    public DateTime? lastupd { get; set; }
}
