public class GetTrackedTasks
{
    public long id { get; set; }
    public long? site { get; set; }
    public long? tskgrp { get; set; }
    public long? tskresp { get; set; }
    public long? allocto { get; set; }
    public long? actref { get; set; }
    public string desc { get; set; }
    public string reldesc { get; set; }
    public DateTime dateadd { get; set; }
    public DateTime livedate { get; set; }
    public DateTime? expdate { get; set; }
    public DateTime? compdate { get; set; }
    public long? compby { get; set; }
    public short? acttt { get; set; }
    public long? prio { get; set; }
    public byte stat { get; set; }
    public byte type { get; set; }
    public string ttext { get; set; }
    public string tfunc { get; set; }
    public string tparam { get; set; }
    public byte relobjtyp { get; set; }
    public long? rvid { get; set; }
    public long? camaud { get; set; }
    public long? resatt { get; set; }
    public bool trkbook { get; set; }
    public string trkoffset { get; set; }
    public long? persnot { get; set; }
    public long? subid { get; set; }
    public long? postran { get; set; }
    public long? relpers { get; set; }
    public long? relcase { get; set; }
    public bool autocnc { get; set; }
    public string resch { get; set; }
    public DateTime? reunt { get; set; }
    public long? partl { get; set; }
    public short? alarmmin { get; set; }
    public long? batch { get; set; }
    public DateTime? lastupd { get; set; }
}
