public class GetTimeZones
{
    public long id { get; set; }
    public long grp { get; set; }
    public string desc { get; set; }
    public int? stmo1 { get; set; }
    public int? etmo1 { get; set; }
    public int? stmo2 { get; set; }
    public int? etmo2 { get; set; }
    public int? stmo3 { get; set; }
    public int? etmo3 { get; set; }
    public int? sttu1 { get; set; }
    public int? ettu1 { get; set; }
    public int? sttu2 { get; set; }
    public int? ettu2 { get; set; }
    public int? sttu3 { get; set; }
    public int? ettu3 { get; set; }
    public int? stwe1 { get; set; }
    public int? etwe1 { get; set; }
    public int? stwe2 { get; set; }
    public int? etwe2 { get; set; }
    public int? stwe3 { get; set; }
    public int? etwe3 { get; set; }
    public int? stth1 { get; set; }
    public int? etth1 { get; set; }
    public int? stth2 { get; set; }
    public int? etth2 { get; set; }
    public int? stth3 { get; set; }
    public int? etth3 { get; set; }
    public int? stfr1 { get; set; }
    public int? etfr1 { get; set; }
    public int? stfr2 { get; set; }
    public int? etfr2 { get; set; }
    public int? stfr3 { get; set; }
    public int? etfr3 { get; set; }
    public int? stsa1 { get; set; }
    public int? etsa1 { get; set; }
    public int? stsa2 { get; set; }
    public int? etsa2 { get; set; }
    public int? stsa3 { get; set; }
    public int? etsa3 { get; set; }
    public int? stsu1 { get; set; }
    public int? etsu1 { get; set; }
    public int? stsu2 { get; set; }
    public int? etsu2 { get; set; }
    public int? stsu3 { get; set; }
    public int? etsu3 { get; set; }
    public int? stbh1 { get; set; }
    public int? etbh1 { get; set; }
    public int? stbh2 { get; set; }
    public int? etbh2 { get; set; }
    public int? stbh3 { get; set; }
    public int? etbh3 { get; set; }
    public bool ignbh { get; set; }
    public bool ignforbh { get; set; }
    public long? batch { get; set; }
    public DateTime? lastupd { get; set; }
}
