public class LoadPositemsForWebGroup
{
    public long posItemID { get; set; }
    public string productCode { get; set; }
    public string description { get; set; }
    public string ldesc { get; set; }
    public long? pitimage { get; set; }
    public string nlCode { get; set; }
    public string nlgrp { get; set; }
    public string txCode { get; set; }
    public int loyaltyPoints { get; set; }
    public DateTime? startDate { get; set; }
    public DateTime? endDate { get; set; }
    public bool manalloc { get; set; }
    public int defaultQuantity { get; set; }
    public long? defaultCommission { get; set; }
    public string tillMessage { get; set; }
    public int noOfRecipts { get; set; }
    public short Sequence { get; set; }
    public string barCodeNo { get; set; }
    public int btnColour { get; set; }
    public int txtColour { get; set; }
    public string btnText { get; set; }
    public decimal defaultPrice { get; set; }
    public bool active { get; set; }
    public bool chkstock { get; set; }
    public bool allrfnd { get; set; }
    public bool upsl { get; set; }
    public bool prtpnts { get; set; }
    public byte posType { get; set; }
    public bool ebEntity { get; set; }
    public bool datpi { get; set; }
    public byte datpitype { get; set; }
    public long? package { get; set; }
    public bool requiresMember { get; set; }
    public bool requiresTableNo { get; set; }
    public long? stockID { get; set; }
    public long? POSRentalsID { get; set; }
    public long? POSExtrasID { get; set; }
    public byte vatType { get; set; }
    public string receiptText { get; set; }
    public string remid { get; set; }
    public string remgrp { get; set; }
    public string reminfo { get; set; }
    public bool fpri { get; set; }
    public bool frefpri { get; set; }
    public bool usegrp { get; set; }
    public bool postrem { get; set; }
    public long? canbuy { get; set; }
    public bool lnkmsg { get; set; }
    public byte refundtype { get; set; }
    public byte PartyDiscountType { get; set; }
    public long? batch { get; set; }
    public DateTime? lastupd { get; set; }
}
