public class PackagesForSubscription
{
    public decimal? maxprice { get; set; }
    public decimal? minprice { get; set; }
    public long id { get; set; }
    public string desc { get; set; }
    public string longdesc { get; set; }
    public string webdesc { get; set; }
    public long? UpsellOption { get; set; }
    public decimal? PackagePrice { get; set; }
    public short minreq { get; set; }
    public short maxall { get; set; }
    public bool charge { get; set; }
    public short seq { get; set; }
    public bool incpric { get; set; }
    public bool? ispackprice { get; set; }
    public long groupid { get; set; }
    public string groupdesc { get; set; }
    public string groupwebdesc { get; set; }
    public long itemid { get; set; }
    public bool syncoth { get; set; }
    public bool defsel { get; set; }
    public bool supdisp { get; set; }
    public short itemseq { get; set; }
    public long? beid { get; set; }
    public long? begrp { get; set; }
    public short? usubk { get; set; }
    public string bedesc { get; set; }
    public string belongdesc { get; set; }
    public long? intprof { get; set; }
    public byte? minage { get; set; }
    public byte? maxage { get; set; }
    public long? cceid { get; set; }
    public string ccedesc { get; set; }
    public string ccelongdesc { get; set; }
    public long? ccecat { get; set; }
    public int? cceminatt { get; set; }
    public int? ccemaxatt { get; set; }
}
