public class Prices
{
    public long id { get; set; }
    public long? site { get; set; }
    public string desc { get; set; }
    public string lk1 { get; set; }
    public string lk2 { get; set; }
    public string lk3 { get; set; }
    public long? memstat { get; set; }
    public long? svdeflv { get; set; }
    public long? memprf { get; set; }
    public long? viptyp { get; set; }
    public long? tzon { get; set; }
    public string mins { get; set; }
    public long? res { get; set; }
    public long? able { get; set; }
    public int? prof { get; set; }
    public long? bent { get; set; }
    public long? begrp { get; set; }
    public long? cceid { get; set; }
    public long? ccegrp { get; set; }
    public long? creid { get; set; }
    public long? creage { get; set; }
    public long? package { get; set; }
    public bool packpri { get; set; }
    public long? facil { get; set; }
    public string extint { get; set; }
    public string extintcod { get; set; }
    public long? curr { get; set; }
    public long? prodpi { get; set; }
    public decimal? price { get; set; }
    public long? cncpi { get; set; }
    public decimal? cncprice { get; set; }
    public long? rokcnc { get; set; }
    public long? credpi { get; set; }
    public decimal? crprice { get; set; }
    public decimal? loyptcrd { get; set; }
    public decimal? loyptdeb { get; set; }
    public decimal? disco { get; set; }
    public DateTime? acfrom { get; set; }
    public DateTime? acto { get; set; }
    public bool isret { get; set; }
    public short seqno { get; set; }
    public long? movepi { get; set; }
    public decimal? moveprice { get; set; }
    public short? MinAge { get; set; }
    public short? MaxAge { get; set; }
    public short? MinAgeMonths { get; set; }
    public short? MaxAgeMonths { get; set; }
    public long? batch { get; set; }
    public DateTime? lastupd { get; set; }
}
