public class ReservationsForResourceGroupNew
{
    public long resid1 { get; set; }
    public long resid2 { get; set; }
    public long rvid { get; set; }
    public long? beid { get; set; }
    public long? cceocc { get; set; }
    public string note { get; set; }
    public byte resstat { get; set; }
    public int? unpaid { get; set; }
    public int? paspos { get; set; }
    public decimal? balance { get; set; }
    public long? relpers { get; set; }
    public string sn { get; set; }
    public string fn { get; set; }
    public long rlid { get; set; }
    public DateTime lstdate { get; set; }
    public DateTime lendate { get; set; }
    public string bedesc { get; set; }
    public string ccedesc { get; set; }
    public string cceoccdesc { get; set; }
    public string ccemnem { get; set; }
    public long? beappear { get; set; }
    public string bemnem { get; set; }
    public int? numatt { get; set; }
    public long? catapp { get; set; }
    public int? numwait { get; set; }
    public int? minatt { get; set; }
    public int? maxatt { get; set; }
    public long? ccegapp { get; set; }
    public string ccegdesc { get; set; }
    public string ccegmnem { get; set; }
    public string ccecdesc { get; set; }
    public string ccecmnem { get; set; }
    public string remid { get; set; }
    public string remnum { get; set; }
    public long? cceapp { get; set; }
    public long? cceid { get; set; }
    public long? emptygroup { get; set; }
    public long? fullgroup { get; set; }
    public long? emptycce { get; set; }
    public long? fullcce { get; set; }
    public long? appeartu { get; set; }
    public long? appearlf { get; set; }
    public int? tui { get; set; }
    public int? left { get; set; }
    public short? bookatt { get; set; }
    public short? bookgam { get; set; }
    public long? tran { get; set; }
    public bool reslk { get; set; }
    public bool timelk { get; set; }
    public long? pack { get; set; }
    public long? appearwaiver { get; set; }
    public int? numsess { get; set; }
    public int? cursess { get; set; }
    public string packdesc { get; set; }
}
